version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: rest_api
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        networks:
            - laravel

    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
